### PR TITLE
Support for comments

### PR DESCRIPTION
**Pull request by schuellerf**
quick and dirty implementation to show comments

### CODE REVIEW

**Review by phipsgabler — COMMENTED** [review]
That was on my todo list already, thanks. 

As far as I understand, `print_card` now iterates over _all_ actions every time, so we have O(#cards \* #actions) checks. Could you implement it in such a way that all comments are at once extracted into a dictionary of lists or something like that, and this then gets passed to `print_card`? If the comments flag is `False`, you could just give it an empty dictionary.

**Comment by schuellerf** [comment]
although I don't have a board where this might have a real impact on runtime
sure I'll change that...

**Comment by phipsgabler** [comment]
I actually expected that argument ;) It just felt wrong to me. Thanks for changing.

Now that I have found time, I reformatted the output a bit, so that it becomes a markdown list with prepended information. What do you think?

**Comment by schuellerf** [comment]
Looks nice! The next thing would be i18n :)
Before my edits only content of trello itself was printed ...

**Comment by phipsgabler** [comment]
I have already thought about adding something like config files, but not really worked it out. There's now an issue #3 where we can discuss this.

**Pull request merged**
