### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by schuellerf**
Hi!
Today I was basically too lazy to install the pandoc pdf stuff again, so here is an initial version with docker support - if you're interrested.

### CODE REVIEW

**Comment by phipsgabler** [comment]
Hi,

sorry for letting you wait. When trying `USE_DOCKER=1 make pdf` (on Ubuntu), it asks me for sudo for changing some file permissions:

```
...
0d27bc851ca6: Pull complete 
Digest: sha256:d8c318f5570f79ff6a84c999b908126ae9da9342b8d58f1a9c8546aea441d3a1
Status: Downloaded newer image for marcelhuberfoo/pandoc-gitit:latest
echo "Set permissions of docker-created files back again"
Set permissions of docker-created files back again
sudo chown -R philipp:philipp build
[sudo] password for philipp: 
```

I haven't used docker before. Is that normal/intended/neccessary?

Other than that, this looks like a nice option, and I'll merge it after this question is resolved.

Thanks!

**Comment by schuellerf** [comment]
This is due to the docker container runs as root inside - which is not really nice, but the default
I think I could change that somehow... I'll check

**Comment by phipsgabler** [comment]
Hm, this causes another permission error on my machine:

```
python3 ./src/trello2md.py --output build/export.md export.json --comments --header
Sucessfully translated to "build/export.md"!
docker run --env "UNAME=1000:1000" --volume /home/philipp/git/trello2md:/data marcelhuberfoo/pandoc-gitit pandoc -f markdown -t latex build/export.md -o build/export.pdf --template=tex/trello.latex --latex-engine=xelatex "--variable=title:export" 
pandoc: build/export.pdf: openBinaryFile: permission denied (Permission denied)
Makefile:77: recipe for target 'build/export.pdf' failed
make: *** [build/export.pdf] Error 1
```

However, I have found it to work with changing the command to:

```
MDPROC = docker run --volume $(shell pwd):/data:z marcelhuberfoo/pandoc-gitit pandoc
```

(see [here](https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/)). Does that work for you, too?

**Comment by schuellerf** [comment]
Did you do remove the build/ directory before trying the new version?

**Comment by schuellerf** [comment]
For me it works when having _both_ UNAME set and ":z" option on the volume. (see last commit)
Setting this UNAME should be fine for selinux also.

if you still have problems, please send me the output of
`ls -lZ ; ls -lZ build/`
before and after you run make

**Comment by phipsgabler** [comment]
Works now, great. 

Thanks again for your contributions!

**Pull request merged**
